if(['/research/it-gets-better/','/research/population-health-innovation-lab/'].includes(location.pathname.replace(/\/?$/, '/')))location.replace('/community/ucla/datatalks/');

const escapeHTML=value=>String(value||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const assetFigure=a=>a.type==='video'?`<figure class="asset-figure video-figure"><video controls playsinline preload="none" poster="${a.poster}" aria-label="${escapeHTML(a.name)}"><source src="${a.src}" type="video/mp4"></video><figcaption>${escapeHTML(a.name)}</figcaption></figure>`:a.type==='pdf'?`<figure class="asset-figure pdf-figure"><a href="${a.src}" target="_blank" rel="noopener noreferrer"><img src="${a.thumb}" width="${a.width}" height="${a.height}" loading="lazy" alt="${escapeHTML(a.name)} — PDF preview"><span class="pdf-link">${escapeHTML(a.name)} · Open PDF ↗</span></a></figure>`:`<figure class="asset-figure ${a.width>a.height?'landscape':'portrait'} ${a.featuredPreview?'featured-preview':''}"><button class="asset-open" type="button" data-image="${a.src}" data-alt="${escapeHTML(a.alt)}" data-caption="${escapeHTML(a.caption)}" aria-label="Enlarge ${escapeHTML(a.alt)}"><img src="${a.displaySrc||a.thumb||a.src}" width="${a.width}" height="${a.height}" loading="${a.eagerPreview?'eager':'lazy'}" decoding="async" alt="${escapeHTML(a.alt)}"></button></figure>`;
const assetGallery=items=>`<div class="asset-gallery">${items.map(assetFigure).join('')}</div>`;
const gallerySections=groups=>(groups||[]).map(g=>`<section class="asset-section ${g.layout||''}">${g.title?`<h3>${escapeHTML(g.title)}</h3>`:''}${g.description?`<p class="gallery-description">${escapeHTML(g.description)}</p>`:''}${g.eventGroups?g.eventGroups.map(e=>`<section class="event-pair"><div class="event-pair-heading"><h4>${escapeHTML(e.title)}</h4></div><div class="event-pair-photos">${e.items.map(a=>`<div class="dated-photo ${a.width>a.height?'event-landscape':'event-portrait'}"><span class="photo-year">(${a.eventIndex}) / ${a.year}</span>${assetFigure(a)}</div>`).join('')}</div></section>`).join(''):assetGallery(g.items)}</section>`).join('');
const eventSections=groups=>{let rows=[],row=[],count=0;for(const g of groups){const n=g.rowSlots||Math.min(g.items.length,6);if(count+n>6&&row.length){rows.push(row);row=[];count=0;}row.push(g);count+=n;if(g.newRowAfter){rows.push(row);row=[];count=0;}}if(row.length)rows.push(row);return `<div class="events-compact">${rows.map(row=>`<div class="event-row">${row.map(g=>`<section class="event-group" style="--slots:${g.rowSlots||Math.min(g.items.length,6)};--poster-columns:${g.posterColumns||g.rowSlots||Math.min(g.items.length,6)}"><h3>${escapeHTML(g.title)}</h3><div class="event-posters">${g.items.map(assetFigure).join('')}</div></section>`).join('')}</div>`).join('')}</div>`;};
const mediaCollection=g=>{if(g.title==='On-Campus Housing Council Events')return eventSections(g.groups);return `<div class="compact-media ${g.title==='Wallpapers'?'compact-wallpapers':''}">${g.groups?gallerySections(g.groups):assetGallery(g.items)}</div>`;};
const projectLogo=p=>p.logo?`<img class="organization-logo" src="${p.logo}" alt="${escapeHTML(p.title)} logo">`:'';
const subCover=(p,i)=>{const a=p.galleries?.[i]?.items.find(x=>x.type==='image'||x.type==='pdf');return a?`<div class="collection-cover"><img src="${a.displaySrc||a.thumb||a.src}" alt="" loading="lazy"><span>${p.galleries[i].items.length} items</span></div>`:`<div class="art-space">${p.subs[i]}</div>`;};


const calendarMarkup=g=>`<section class="asset-section calendar-section"><h3>Cards</h3><div class="calendar" tabindex="0" aria-label="Card book. Use up and down arrows to flip"><div class="calendar-rings" aria-hidden="true"></div><div class="calendar-sheet"></div><div class="calendar-leaf" aria-hidden="true"></div></div><div class="calendar-controls"><button type="button" id="card-prev" aria-label="Previous card">↑</button><span id="card-status" role="status" aria-live="polite"></span><button type="button" id="card-next" aria-label="Next card">↓</button></div></section>`;
const butterflyMarkup=g=>`<section class="asset-section butterfly-editorial"><h3>Butterflies</h3><div class="butterfly-contact-sheet">${g.items.map((a,i)=>`<div class="butterfly-study study-${i%8}"><span class="study-index" aria-hidden="true">(${String(i+1).padStart(2,'0')})</span>${assetFigure(a)}</div>`).join('')}</div></section>`;
const sketchbookMarkup=()=>`<div class="sketchbook" aria-label="Interactive sketchbook"><div class="book" tabindex="0" aria-label="Sketchbook. Use left and right arrow keys to turn pages"><div class="book-page left-page" id="left-page"></div><div class="book-page right-page" id="right-page"></div><div class="turning-leaf" aria-hidden="true"></div></div><div class="book-controls"><button id="prev-page" aria-label="Previous pages">← <span>Previous</span></button><span id="page-status" role="status" aria-live="polite"></span><button id="next-page" aria-label="Next pages"><span>Next</span> →</button></div></div>`;
const playgroundMarkup=()=>{const byTitle=t=>playgroundCollections.find(g=>g.title===t);const cats=byTitle('Drawings'),sketches=byTitle('sketches');return butterflyMarkup(byTitle('butterflies'))+gallerySections([{...byTitle('cards'),items:byTitle('cards').items.map(a=>({...a,eagerPreview:true,displaySrc:a.thumb+'?v=2'})),title:'Cards',layout:'cards-collage'}])+`<section class="asset-section sketches-collection"><h3>Sketches</h3><div class="digitals-row people-sketches-row">${assetGallery(sketchbookAssets)}</div><div class="drawing-pair">${assetGallery(cats.items)}${assetGallery(sketches.items)}</div></section>`+gallerySections([{...byTitle('digitals'),title:'Digitals',layout:'digitals-row'}]);};

const art=(n,color='')=>`<div class="art-space ${color}"><span class="placeholder"><b>${String(n).padStart(2,'0')}</b>Artwork to come</span></div>`;
const path=location.pathname.split('/').filter(Boolean);const section=path[0]==='work'?'media':path[0]||'home';
document.body.dataset.section=section;document.body.dataset.group=path[1]||'';
document.querySelectorAll('nav a').forEach(a=>{if((a.pathname.split('/').filter(Boolean)[0]||'home')===section)a.setAttribute('aria-current','page')});
const tile=(p,i,base)=>`<a class="tile" href="/${base}/${p.slug}/"><div class="art-space project-cover ${i%2?'blue':''}"><span class="cover-index">0${i+1}</span><span>${p.title}</span></div><h2>${p.title}<span>↗</span></h2><span class="meta">${p.dates}</span></a>`;
const communityCover=(p,i)=>`<a class="tile community-preview" href="/community/${p.slug}/"><div class="community-art community-art-${i}" aria-hidden="true"><svg viewBox="0 0 800 460" preserveAspectRatio="xMidYMid slice"><defs><pattern id="community-grid-${i}" width="38" height="38" patternUnits="userSpaceOnUse"><path d="M38 0H0V38" fill="none" stroke="#173e6b" stroke-opacity=".16" stroke-width=".7"/></pattern><pattern id="community-dots-${i}" width="5" height="5" patternUnits="userSpaceOnUse"><circle cx="2" cy="2" r=".9" fill="${i?'#982e3c':'#2357ba'}" opacity=".45"/></pattern></defs><rect width="800" height="460" fill="url(#community-grid-${i})"/><path d="${i?'M380 45L745 95L685 400L420 350Z':'M450 55L714 87L746 359L395 400Z'}" fill="url(#community-dots-${i})"/><g fill="none" stroke="#193f71" stroke-width=".8" opacity=".65">${i?`<ellipse cx="540" cy="230" rx="218" ry="137" transform="rotate(-28 540 230)"/><ellipse cx="540" cy="230" rx="180" ry="137" transform="rotate(28 540 230)"/>`:`<ellipse cx="566" cy="232" rx="174" ry="145" transform="rotate(-22 566 232)"/><ellipse cx="566" cy="232" rx="174" ry="108" transform="rotate(32 566 232)"/><circle cx="566" cy="232" r="123" stroke-opacity=".45"/>`}<path d="M290 390L745 40M340 40L710 410M280 230H790M540 10V450"/></g><path d="M40 370L760 100" stroke="${i?'#ac2b36':'#254fab'}" stroke-width="1" fill="none"/><g fill="${i?'#172b44':'#2356be'}"><rect x="${i?435:650}" y="85" width="32" height="32"/><circle cx="650" cy="320" r="${i?22:8}"/></g><circle cx="${i?490:490}" cy="${i?140:340}" r="17" fill="${i?'#fff':'#14202d'}" stroke="#183652" stroke-width=".8"/><g stroke="${i?'#a72938':'#2451b3'}"><path d="M70 68h16M78 60v16M724 383h16M732 375v16"/></g></svg><span class="community-cover-number">0${i+1}</span><span class="community-cover-name">${i?'Go/<em>Weiqi</em>':'UCLA'}</span><span class="community-cover-rule"></span></div><h2>${p.title}<span>↗</span></h2><span class="meta">${p.dates}</span></a>`;
const row=(p,i,base)=>`<button type="button" class="research-item research-trigger" data-research="${p.slug}" aria-haspopup="dialog"><span class="meta">0${i+1}</span><div>${projectLogo(p)}<h2>${p.title}</h2><p>${p.role}</p><span class="meta">${p.dates}</span></div><span>↗</span></button>`;
const nestedProjects=p=>(p.projects||[]).map(project=>`<section class="consulting-project" id="${project.slug}"><h3>${project.title}</h3><p class="meta">${project.role} · ${project.dates}</p><p>${project.description}</p></section>`).join('');
const goJourneyMarkup=awards=>`<div class="go-journey-awards">${awards.map((award,i)=>`<section class="go-journey-award ${award.photos.length?'with-photos':''}"><div class="go-journey-award-copy"><span class="meta">${String(i+1).padStart(2,'0')}</span><h3>${escapeHTML(award.title)}</h3></div>${award.photos.length?`<div class="go-journey-photos">${award.photos.map(assetFigure).join('')}</div>`:''}</section>`).join('')}</div>`;
const studentLifeMarkup=data=>`<div class="student-life-details">
<section class="student-life-section student-life-international"><div class="student-life-heading"><h3>LinkedIn</h3></div><div class="student-life-copy"><div class="student-life-stats"><div><strong>4.3k+</strong><span>followers</span></div></div><article class="linkedin-featured-post" aria-label="Featured LinkedIn post"><div class="linkedin-post-heading"><h4>Featured post</h4><div class="student-life-stats post-stats"><div><strong>650k+</strong><span>impressions on this post</span></div><div><strong>2.9k+</strong><span>likes on this post</span></div></div></div><a class="text-link" href="${escapeHTML(data.postUrl)}" target="_blank" rel="noopener noreferrer">Read the original LinkedIn post ↗</a><blockquote class="student-life-post">${data.post.map(p=>`<p>${escapeHTML(p)}</p>`).join('')}</blockquote></article></div></section>
<section class="student-life-section"><div class="student-life-heading"><h3>RedNote</h3></div><div class="student-life-copy"><div class="student-life-stats"><div><strong>1.7k+</strong><span>followers</span></div><div><strong>100+</strong><span>study materials shared</span></div><div><strong>40k+</strong><span>learners reached online</span></div><div><strong>30+</strong><span>students directly mentored</span></div></div></div></section>
<section class="student-life-section"><div class="student-life-heading"><h3>Campus Tours</h3></div><div class="student-life-copy"><div class="student-life-stats"><div><strong>20+</strong><span>campus tours</span></div><div><strong>2-50</strong><span>group sizes</span></div></div><ul class="student-life-bullets"><li>Shared student life and personal experiences with families and students ranging from kindergarteners to college students, including prospective Bruins and visitors from around the world.</li><li>Practiced walking backwards and projecting my voice without a microphone.</li></ul></div></section>
</div>`;
const communityRow=(p,i)=>`<button type="button" class="research-item community-trigger" data-community="${p.slug}" aria-haspopup="dialog"><span class="meta">0${i+1}</span><span class="community-row-copy">${projectLogo(p)}<span class="community-row-title">${p.title}</span><span class="community-row-role">${p.role}</span><span class="meta">${p.dates}</span></span><span aria-hidden="true">↗</span></button>`;
const detail=(p,base)=>`<article class="page"><a class="text-link" href="/${base}/">← Back</a><div class="detail-head">${projectLogo(p)}<h1 class="page-title">${p.title}</h1><p class="meta">${p.role}${p.dates?' · '+p.dates:''}</p></div><div class="body-copy"><h2>Overview</h2><p>${p.description}</p></div>${gallerySections(p.galleries)}</article>`;
let content='';
if(section==='home')content=`<section class="hero"><div class="orbit" aria-hidden="true"></div><div class="hero-words fade-in"><div class="word-row"><span class="num">01</span><a href="/media/">Exploring media,</a></div><div class="word-row"><span class="num">02</span><a href="/research/">conducting research,</a></div><div class="word-row"><span class="num">03</span><a href="/community/">building communities.</a></div></div><a class="play-note" href="/playground/"><span class="play-icon" aria-hidden="true">✎</span><span><small>04</small>My Playground</span></a><div class="hero-bottom"><button class="pattern-toggle" type="button" aria-label="Remix the dot pattern" aria-pressed="false">✳</button></div></section><section class="intro" id="hello"><div><span class="eyebrow">Hi, I'm</span><h1 class="signature"><span class="name-first">Julia</span> <span class="name-last">Zhang</span></h1></div><div><p>Cognitive Science @ UCLA<br>Beijing · Vancouver · Los Angeles</p><a class="text-link" href="/media/">Explore more ↗</a></div></section>`;
else if(section==='media'&&!path[1])content=`<section class="page"><div class="media-masthead"><div class="media-art" aria-hidden="true"><span class="media-collage-image"></span><span class="media-collage-paper"></span><span class="media-collage-stripes"></span><span class="media-collage-dots"></span><svg class="media-collage-line" viewBox="0 0 100 300" preserveAspectRatio="none"><path d="M12 4 L88 294 L12 272 Z" fill="none" stroke="currentColor" stroke-width="0.8" vector-effect="non-scaling-stroke"/></svg></div><h1 class="page-title">Media</h1></div><div class="grid">${media.map((p,i)=>tile(p,i,'media')).join('')}</div></section>`;
else if(section==='media'&&media.some(p=>p.slug===path[1])){const p=media.find(p=>p.slug===path[1]);const n=path[2]?p.subs.findIndex((_,i)=>path[2]===`sub-project-${i+1}`):-1;
if(!path[2])content=`<article class="page"><a class="text-link" href="/media/">← All media</a><h1 class="page-title media-detail-title">${p.title}</h1><p class="meta">${p.role} · ${p.dates}</p>${p.description?`<div class="detail-info"><p>${p.description}</p></div>`:''}${p.slug==='ucla-student-affairs'?p.galleries.map(g=>`<section class="asset-section student-direct">${g.title==='Designs & communications'?'':`<h3>${escapeHTML(g.title)}</h3>`}${mediaCollection(g)}</section>`).join(''): `<div class="sub-grid">${p.subs.map((t,i)=>`<button type="button" class="sub-card" data-sub="${i}" aria-haspopup="dialog">${subCover(p,i)}<h2>${t} ↗</h2></button>`).join('')}</div>`}</article>`;
else if(n>=0)content=`<article class="page"><a class="text-link" href="/media/${p.slug}/">← ${p.title}</a><h1 class="page-title">${p.subs[n]}</h1>${mediaCollection(p.galleries[n])}</article>`;}
else if(section==='research'&&(!path[1]||research.some(p=>p.slug===path[1])))content=`<section class="page"><h1 class="page-title">Research</h1><div class="research-list">${research.map((p,i)=>row(p,i,'research')).join('')}</div></section>`;
else if(section==='research'&&research.some(p=>p.slug===path[1]))content=detail(research.find(p=>p.slug===path[1]),'research');
else if(section==='community'&&!path[1])content=`<section class="page"><h1 class="page-title">Community</h1><div class="grid">${[{slug:'ucla',title:'UCLA',dates:'DataTalks Consulting · Rye International · Miscellaneous Student Life'},{slug:'go-community',title:'Go/Weiqi',dates:'Intercollegiate / Regional / National / International'}].map((p,i)=>communityCover(p,i)).join('')}<button type="button" class="project-card community-cover werewolf-community-trigger" data-werewolf-story aria-haspopup="dialog"><div class="community-cover-art" style="background:#191b17;color:#ded7c4;min-height:260px;display:flex;align-items:center;justify-content:center;flex-direction:column;gap:18px"><span style="font-size:50px">☾</span><span style="font:26px Georgia,serif">天黑，请说心里话。</span><span style="font:10px monospace;letter-spacing:3px">THE NIGHT LETTERS</span></div><h2>Werewolf / 狼人杀<span>↗</span></h2></button></div></section>`;
else if(section==='community'&&communities[path[1]]){const group=communities[path[1]],base='community/'+path[1];if(!path[2]||group.some(p=>p.slug===path[2]))content=`<section class="page"><a class="text-link" href="/community/">← All community</a><h1 class="page-title">${path[1]==='ucla'?'UCLA':'Go/Weiqi'}</h1><div class="research-list">${group.map(communityRow).join('')}</div></section>`;}
else if(section==='playground')content=`<section class="page playground-page"><h1 class="page-title">Playground</h1>${playgroundMarkup()}</section>`;
else if(section==='contact')content=`<section class="page contact-page"><h1 class="page-title">Let’s connect.</h1><div class="flight-stage" aria-hidden="true"><svg class="auto-plane" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1" stroke-linecap="round" stroke-linejoin="round"><path d="M22 2 14 22 9 15 2 10 22 2Z" fill="#ffffff"/><path d="M22 2 9 15" fill="none"/></svg></div><div class="contacts contact-reveal"><a class="contact-row" href="mailto:jyqzhang@ucla.edu"><span>Email ↗</span><span>jyqzhang@ucla.edu</span></a><a class="contact-row" href="https://www.linkedin.com/in/julia-yuqing-zhang" target="_blank" rel="noopener noreferrer"><span>LinkedIn ↗</span><span>https://www.linkedin.com/in/julia-yuqing-zhang</span></a></div></section>`;
if(!content)content=`<section class="page"><h1 class="page-title">Page not found.</h1><a href="/">Back home →</a></section>`;
document.querySelector('main').innerHTML=content;document.title=section==='home'?"Julia Zhang's Portfolio":`${section.charAt(0).toUpperCase()+section.slice(1)} — Julia Zhang Portfolio`;
// Replace each empty src with an individual supplied image; the book preserves its full aspect ratio.
const sketchPages=sketchbookAssets.map(a=>({...a,caption:a.name}));
if(section==='playground' && document.querySelector('.book')){
 let spread=0,busy=false;const book=document.querySelector('.book'),left=document.querySelector('#left-page'),right=document.querySelector('#right-page'),leaf=document.querySelector('.turning-leaf'),prev=document.querySelector('#prev-page'),next=document.querySelector('#next-page');
 const page=(i)=>{const p=sketchPages[i];return p?`<div class="page-image">${p.src?`<img src="${p.src}" alt="${p.alt}">`:`<span class="sketch-placeholder"><span>${p.caption}</span><small>Image to come</small></span>`}</div><span class="page-number">${i+1}</span>`:'<span class="sketch-placeholder">The end</span>';};
 function render(){left.innerHTML=page(spread*2);right.innerHTML=page(spread*2+1);prev.disabled=spread===0;next.disabled=spread>=Math.ceil(sketchPages.length/2)-1;document.querySelector('#page-status').textContent=`${spread*2+1}–${Math.min(spread*2+2,sketchPages.length)} / ${sketchPages.length}`;}
 const warmed=sketchPages.map(p=>{const img=new Image();img.src=p.src;img.decode?.().catch(()=>{});return img;});
 function flip(dir){if(busy||spread+dir<0||spread+dir>=Math.ceil(sketchPages.length/2))return;
 const oldLeft=left.innerHTML,oldRight=right.innerHTML;spread+=dir;
 if(matchMedia('(prefers-reduced-motion: reduce)').matches){render();return;}
 busy=true;render();const newLeft=left.innerHTML,newRight=right.innerHTML;
 if(dir>0)left.innerHTML=oldLeft;else right.innerHTML=oldRight;
 leaf.innerHTML=`<div class="leaf-front">${dir>0?oldRight:oldLeft}</div><div class="leaf-back">${dir>0?newLeft:newRight}</div>`;
 leaf.className='turning-leaf '+(dir>0?'forward':'backward');
 const animation=leaf.animate([{transform:'rotateY(0deg)'},{transform:`rotateY(${dir>0?-180:180}deg)`}],{duration:420,easing:'cubic-bezier(.22,.65,.3,1)',fill:'forwards'});
 animation.onfinish=()=>{render();leaf.className='turning-leaf';leaf.innerHTML='';animation.cancel();busy=false;};
 }

 prev.addEventListener('click',()=>flip(-1));next.addEventListener('click',()=>flip(1));book.addEventListener('keydown',e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();flip(e.key==='ArrowRight'?1:-1);}});
 let startX=0;book.addEventListener('pointerdown',e=>{startX=e.clientX;});book.addEventListener('pointerup',e=>{const dx=e.clientX-startX;if(Math.abs(dx)>45)flip(dx<0?1:-1);else flip(e.clientX<book.getBoundingClientRect().left+book.clientWidth/2?-1:1);});render();
}

const subButtons=document.querySelectorAll('[data-sub]');
if(subButtons.length){
 const project=media.find(p=>p.slug===path[1]);
 const dialog=document.createElement('dialog');dialog.className='project-modal';dialog.setAttribute('aria-labelledby','modal-title');
 dialog.innerHTML='<div class="modal-toolbar"><span>'+project.title+'</span><button type="button" class="modal-close" aria-label="Close project">Close ×</button></div><div class="modal-content"></div>';
 document.body.append(dialog);let trigger;
 for(const button of subButtons)button.addEventListener('click',()=>{trigger=button;const n=Number(button.dataset.sub);dialog.classList.toggle('events-modal',project.galleries[n].title==='On-Campus Housing Council Events');dialog.classList.toggle('wallpapers-modal',project.galleries[n].title==='Wallpapers');dialog.querySelector('.modal-content').innerHTML=`<h2 id="modal-title">${project.subs[n]}</h2>${mediaCollection(project.galleries[n])}`;dialog.showModal();dialog.scrollTop=0;document.body.classList.add('modal-open');});
 dialog.querySelector('.modal-close').addEventListener('click',()=>dialog.close());
 dialog.addEventListener('close',()=>{dialog.querySelectorAll('video').forEach(video=>video.pause());document.body.classList.remove('modal-open');trigger?.focus({preventScroll:true});});
}

const hero=document.querySelector('.hero');
if(hero){const remix=hero.querySelector('.pattern-toggle');remix.addEventListener('click',()=>{const on=hero.classList.toggle('remix');remix.setAttribute('aria-pressed',String(on));});if(matchMedia('(pointer:fine) and (prefers-reduced-motion:no-preference)').matches){hero.addEventListener('pointermove',e=>{const r=hero.getBoundingClientRect();hero.style.setProperty('--px',((e.clientX-r.left-r.width/2)*.035)+'px');hero.style.setProperty('--py',((e.clientY-r.top-r.height/2)*.035)+'px');});}}
if('IntersectionObserver' in window){const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target);}}),{threshold:.08});document.querySelectorAll('.tile,.research-item,.sub-card,.intro').forEach(el=>{el.classList.add('reveal');observer.observe(el);});}

const pageSurface=document.querySelector('main>.page');
if(pageSurface&&['media','research','community','playground'].includes(section)){
 const motif=document.createElement('div');motif.className='section-motif';motif.setAttribute('aria-hidden','true');
 const patterns={media:'<span class="ascii-layer">+— — — — — —+<br>| / / + / / |<br>| :: ▒▒ :: |<br>+— — — — — —+</span><span class="registration reg-one">+</span><span class="registration reg-two">+</span><span class="signal-bar"></span>',research:'<span class="square s1"></span><span class="square s2"></span><span class="square s3"></span><span class="measure-line"></span>',community:'<span class="collective-word">bringing people together...</span><span class="collective-dots"></span><span class="collective-thread"></span>',playground:'<span class="play-checker"></span><span class="play-dots"></span><span class="play-cross">✳</span><span class="play-ring"></span>'};
 motif.innerHTML=patterns[section]+(section==='media'||section==='playground'?'<span class="micro-strip">+ : : — / /<br>░ ▒ ░ . +<br>/ / — : : +</span>':'');pageSurface.prepend(motif);
}

const communityTriggers=document.querySelectorAll('[data-community]');
if(communityTriggers.length){
 const group=communities[path[1]],dialog=document.createElement('dialog');dialog.className='project-modal community-modal';dialog.setAttribute('aria-labelledby','community-modal-title');
 dialog.innerHTML='<div class="modal-toolbar"><span>'+ (path[1]==='ucla'?'UCLA':'Go/Weiqi')+'</span><button type="button" class="modal-close" aria-label="Close community details">Close ×</button></div><div class="modal-content"></div>';
 document.body.append(dialog);let trigger;
 const openEntry=(button)=>{trigger=button;const entry=group.find(p=>p.slug===button.dataset.community);dialog.dataset.entry=entry.slug;dialog.querySelector('.modal-content').innerHTML=`${projectLogo(entry)}<h2 id="community-modal-title">${entry.title}</h2>${entry.role||entry.dates?`<p class="meta community-role">${[entry.role,entry.dates].filter(Boolean).join(' · ')}</p>`:''}${entry.featured?`<div class="club-feature">${assetFigure(entry.featured)}</div>`:''}<div class="community-overview">${entry.slug==='canadian-go-association'?`<div class="cga-role"><span class="cga-label">2023 CANADIAN GO OPEN</span><h3>Co-Director</h3><p>Largest-ever national Go tournament</p><div class="organizer-honor"><span aria-hidden="true">✳</span><strong>Distinguished Organizer Award</strong></div></div>`:entry.description?`<p>${entry.description}</p>`:''}${nestedProjects(entry)}</div>${entry.awards&&entry.slug!=='canadian-go-association'?`<aside class="go-awards" aria-label="Go awards"><h3>Go awards</h3>${entry.awards.map((a,i)=>`<section><span class="award-index">0${i+1}</span><h4>${escapeHTML(a.title)}</h4><p>${escapeHTML(a.description)}</p></section>`).join('')}</aside>`:''}${entry.studentLife?studentLifeMarkup(entry.studentLife):''}${entry.journeyAwards?goJourneyMarkup(entry.journeyAwards):path[1]==='go-community'?(['canadian-go-association','international'].includes(entry.slug)?gallerySections(entry.galleries.map((g,i)=>({...g,layout:entry.slug==='international'?'go-photo-international international-layout-'+i:'go-photo-canada'}))):eventSections(entry.galleries)):gallerySections(entry.galleries)}`;dialog.showModal();dialog.scrollTop=0;document.body.classList.add('modal-open');};
 communityTriggers.forEach(button=>button.addEventListener('click',()=>openEntry(button)));
 dialog.querySelector('.modal-close').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{dialog.querySelectorAll('video').forEach(video=>video.pause());document.body.classList.remove('modal-open');trigger?.focus({preventScroll:true});});
 if(path[2]){const target=[...communityTriggers].find(b=>b.dataset.community===path[2]);if(target){history.replaceState(null,'','/community/'+path[1]+'/');openEntry(target);}}
}

if(section==='media'&&!path[1]){
 const labels=[['Residential<br><em>Life.</em>','@uclaochc<br>(5k+ on Instagram)'],['Student<br><em>Affairs.</em>','@uclahousing & @uclastudentlife<br>(40k+ on Instagram)']];
 document.querySelectorAll('.tile .project-cover').forEach((cover,i)=>{cover.innerHTML=`${projectLogo(media[i])}<span class="poster-composition" aria-hidden="true"><i class="cover-disc"></i><i class="cover-screen"></i><i class="cover-axis"></i><i class="cover-chip"></i><i class="cover-cross">+</i></span><span class="poster-grid" aria-hidden="true"></span><span class="poster-noise" aria-hidden="true"></span><span class="poster-orbit" aria-hidden="true"></span><span class="poster-title" aria-hidden="true">${labels[i][0]}</span><span class="poster-note" aria-hidden="true">${labels[i][1]}</span><span class="poster-foot" aria-hidden="true"><strong>0${i+1}</strong></span>`;});
}

const imageViewer=document.createElement('dialog');imageViewer.className='image-viewer';imageViewer.setAttribute('aria-label','Artwork enlarged');imageViewer.innerHTML='<button class="viewer-close" aria-label="Close enlarged image">Close ×</button><img alt=""><div class="image-caption" aria-label="Photo caption"></div>';document.body.append(imageViewer);let imageTrigger;
document.addEventListener('click',event=>{const trigger=event.target.closest('[data-image]');if(!trigger)return;imageTrigger=trigger;const img=imageViewer.querySelector('img');img.src=trigger.dataset.image;img.alt=trigger.dataset.alt;imageViewer.querySelector('.image-caption').textContent=trigger.dataset.caption||'';imageViewer.showModal();});
imageViewer.querySelector('button').addEventListener('click',()=>imageViewer.close());imageViewer.addEventListener('close',()=>imageTrigger?.focus({preventScroll:true}));

if(section==='research'){
 const dialog=document.createElement('dialog');dialog.className='project-modal research-modal';dialog.setAttribute('aria-labelledby','research-modal-title');dialog.innerHTML='<div class="modal-toolbar"><span>Research</span><button class="modal-close" aria-label="Close research details">Close ×</button></div><div class="modal-content"></div>';document.body.append(dialog);let trigger;
 const open=button=>{trigger=button;const p=research.find(p=>p.slug===button.dataset.research);dialog.querySelector('.modal-content').innerHTML=`${projectLogo(p)}<h2 id="research-modal-title">${p.title}</h2><p class="meta">${p.role} · ${p.dates}</p><div class="community-overview">${p.description?`<p>${p.description}</p>`:''}${p.website?`<a class="text-link lab-website" href="${p.website}" target="_blank" rel="noopener noreferrer">Visit lab website ↗</a>`:''}${p.studyProjects?`<section class="lab-studies"><h3>Projects</h3>${p.studyProjects.map((study,i)=>`<section class="lab-study"><span class="meta">0${i+1}</span><div><h4>${escapeHTML(study.title)}</h4>${study.description?`<p>${escapeHTML(study.description)}</p>`:''}</div></section>`).join('')}</section>`:''}</div>${gallerySections(p.galleries)}`;dialog.showModal();dialog.scrollTop=0;document.body.classList.add('modal-open');};
 document.querySelectorAll('[data-research]').forEach(b=>b.addEventListener('click',()=>open(b)));dialog.querySelector('button').addEventListener('click',()=>dialog.close());dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');trigger?.focus({preventScroll:true});});
 if(path[1]){const b=document.querySelector(`[data-research="${path[1]}"]`);if(b){history.replaceState(null,'','/research/');open(b);}}
}
if(section==='playground'&&document.querySelector('.calendar')){
 const cards=playgroundCollections.find(g=>g.title==='cards').items,book=document.querySelector('.calendar'),sheet=book.querySelector('.calendar-sheet'),leaf=book.querySelector('.calendar-leaf'),prev=document.querySelector('#card-prev'),next=document.querySelector('#card-next');let current=0,busy=false;
 const render=()=>{sheet.innerHTML=assetFigure(cards[current]);document.querySelector('#card-status').textContent=`${current+1} / ${cards.length}`;prev.disabled=current===0;next.disabled=current===cards.length-1;};
 const turn=dir=>{if(busy||current+dir<0||current+dir>=cards.length)return;busy=true;leaf.innerHTML=`<img src="${cards[current].src}" alt="">`;leaf.className='calendar-leaf '+(dir>0?'flip-up':'flip-down');current+=dir;render();setTimeout(()=>{leaf.className='calendar-leaf';leaf.innerHTML='';busy=false;},matchMedia('(prefers-reduced-motion: reduce)').matches?0:650);};
 prev.addEventListener('click',()=>turn(-1));next.addEventListener('click',()=>turn(1));book.addEventListener('keydown',e=>{if(['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();turn(e.key==='ArrowDown'?1:-1);}});let y;book.addEventListener('pointerdown',e=>y=e.clientY);book.addEventListener('pointerup',e=>{if(Math.abs(e.clientY-y)>45)turn(e.clientY<y?1:-1);});render();
}

if(section==='home'||(section==='community'&&path[1]==='go-community')){
 const surface=section==='home'?document.querySelector('.hero'):document.querySelector('main>.page');
 const decor=document.createElement('div');decor.className='archive-decoration';decor.setAttribute('aria-hidden','true');decor.innerHTML='<svg viewBox="0 0 1000 700" preserveAspectRatio="none"><g fill="none" stroke="currentColor" stroke-width=".65"><path d="M0 530 1000 150M80 700 850 0M0 80 1000 590M30 0V700M970 0V700"/><ellipse cx="710" cy="380" rx="220" ry="280" transform="rotate(35 710 380)"/><circle cx="710" cy="380" r="140"/><path d="M690 380h40M710 360v40M110 90h25M122 78v24"/></g></svg><span class="decor-halftone"></span><span class="decor-registration">+ : : ─ / /<br>░ ▒ ░ . +<br>/ / ─ : : +</span><span class="decor-red"></span>';surface.prepend(decor);
}
if(section==='home'){
 const stage=document.querySelector('.hero'),layer=document.createElement('div');layer.className='hero-play-shapes';
 const specs=[[5,15,'square','#254ccc',14],[84,13,'circle','#a62a39',22],[92,36,'square','#80b6d5',28],[7,70,'ring','#284c8d',30],[58,10,'square','#172435',9],[73,74,'circle','#9dcbd8',16],[42,80,'square','#ae2939',12],[95,72,'ring','#3156aa',36],[28,9,'circle','#88a9d2',9],[17,87,'square','#3156aa',18],[89,54,'cross','#a62a39',20],[65,87,'ring','#1a334f',20]];
 layer.innerHTML=specs.map(([x,y,shape,color,size],i)=>`<button class="play-shape ${shape}" type="button" aria-label="Change color of decorative shape ${i+1}" style="--sx:${x}%;--sy:${y}%;--shape-color:${color};--shape-size:${size}px"></button>`).join('');stage.append(layer);
 const colors=['#254ccc','#ae2939','#80b6d5','#172435','#97c8b8'];layer.querySelectorAll('button').forEach((b,i)=>{let c=i%colors.length;b.addEventListener('click',()=>{c=(c+1)%colors.length;b.style.setProperty('--shape-color',colors[c]);if(!matchMedia('(prefers-reduced-motion: reduce)').matches)b.animate([{transform:'scale(1) rotate(0deg)'},{transform:'scale(1.35) rotate(90deg)'},{transform:'scale(1) rotate(180deg)'}],{duration:420,easing:'ease-out'});});});
 const drawing=document.createElement('div');drawing.className='hero-filigree';drawing.setAttribute('aria-hidden','true');drawing.innerHTML='<svg class="homepage-orbital" viewBox="0 0 650 760" preserveAspectRatio="xMidYMid meet"><defs><pattern id="home-dot-field" width="5" height="5" patternUnits="userSpaceOnUse"><circle cx="1.5" cy="1.5" r=".8" fill="#315ccc" opacity=".27"/></pattern><pattern id="home-dense-dots" width="5" height="5" patternUnits="userSpaceOnUse"><rect x="0" y="0" width="1.7" height="1.7" fill="#3154c8" opacity=".42"/></pattern><pattern id="home-checks" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M0 0H10V10H0ZM10 10H20V20H10Z" fill="#2b4cd4"/></pattern><pattern id="home-hatch" width="5" height="5" patternUnits="userSpaceOnUse"><path d="M1 0V5" stroke="#243d58" stroke-width=".6"/></pattern></defs><path d="M145 40L580 190L590 680L120 610Z" fill="url(#home-dot-field)"/><g fill="none" stroke="#35577a" stroke-width=".65" opacity=".56"><ellipse cx="340" cy="395" rx="285" ry="190" transform="rotate(-32 340 395)"/><ellipse cx="340" cy="395" rx="255" ry="280" transform="rotate(18 340 395)"/><circle cx="385" cy="355" r="184"/><path d="M0 190L620 730M0 720L615 60M45 400H650M305 0V740"/></g><circle cx="389" cy="357" r="174" fill="none" stroke="#b53040" stroke-width=".55" opacity=".6"/><path d="M0 480Q360 120 650 260" fill="none" stroke="#a92537" stroke-width=".8"/><rect x="288" y="267" width="225" height="235" fill="url(#home-dense-dots)" transform="rotate(-15 400 380)"/><rect x="226" y="132" width="80" height="60" fill="url(#home-checks)"/><rect x="445" y="155" width="32" height="32" fill="#2b4cd4"/><rect x="352" y="513" width="174" height="76" fill="url(#home-hatch)" transform="rotate(-12 440 550)" opacity=".5"/><path d="M603 505V528M592 516H615" stroke="#ad2b3d" stroke-width="3"/><circle cx="545" cy="675" r="14" fill="#b52f42"/></svg><i class="micro-bars"></i>';stage.append(drawing);
}
